PROJECT_LIBC_SOURCE_DIR := projects/libc

# $(BUILD_DIR)/$(PROJECT_LIBC_SOURCE_DIR)/.PHONY.DEPENDENCY: ;
$(BUILD_DIR)/$(PROJECT_LIBC_SOURCE_DIR)/libc.so: $(BUILD_DIR)/$(PROJECT_LIBC_SOURCE_DIR)/.PHONY ;

