PROJECT_LIBC_SOURCE_DIR := projects/libc

$(BUILD_DIR)/$(PROJECT_LIBC_SOURCE_DIR)/libc.so: $(BUILD_DIR)/$(PROJECT_LIBC_SOURCE_DIR)/libc.a;
	$(MAKE) -f $(PROJECT_LIBC_SOURCE_DIR)/Makefile \
		DEFAULT_MAKERULE_FILE=Makefile.d/submake_for_custom.mk \
		SOURCE_DIR=$(PROJECT_LIBC_SOURCE_DIR) \
		TARGET=$(@) \
		BUILD_DIR=$(BUILD_DIR)
