
SOURCE_DIR ?= projects/abc

BUILD_DIR ?= build

include projects/abc/Dependency.mk

EXECUTABLE_FILE := $(SOURCE_DIR)/abc
LIBRARY_FILES := $(PROJECTS_ABC_DEPENDENCY)
all: $(BUILD_DIR)/$(EXECUTABLE_FILE) ;

