
SOURCE_DIR ?= .

BUILD_DIR ?= build

include projects/abc/Include.mk

EXECUTABLE_FILE := $(SOURCE_DIR)/abc
OBJECT_FILES := $(PROJECTS_ABC_DEPENDENCY)
all: $(EXECUTABLE_FILE) ;


include $(DEFAULT_MAKERULE_FILE)
